### ISSUE TITLE
zoneChance() never called

### ISSUE THREAD

**Issue by xchopin** [Project-Sloth/ps-dispatch#90]
To follow this closed issue https://github.com/Project-Sloth/ps-dispatch/issues/88

zoneChance() is never called and it's probably an issue
![image](https://user-images.githubusercontent.com/15248061/192347509-23e901b1-d761-4a95-abe7-98f3e7e581e1.png)

**Comment by xchopin** [comment]
you must be trolling at this point

**Comment by pushkart2** [comment]
That is left over code from hunting zones code which we removed because qbcore doesnt have hunting script by default. You are free to PR to use it or remove it but adding a function which is not called doesnt break the script. Plus people who have a hunting script have less work to do. I will leave it open for next 12 hours and then close this issue again.

**Comment by MonkeyWhisper** [comment]
"DevOps Engineer"

**Comment by MonkeyWhisper** [comment]
Thanks Snipe for explaining this, now, closed.
